version: 1
formatters:
  json:
    '()': pythonjsonlogger.jsonlogger.JsonFormatter
    format: '%(asctime)s %(levelname)s %(agent)s %(event)s %(message)s'
    rename_fields:
      asctime: timestamp
      levelname: level
      message: msg
handlers:
  console:
    class: logging.StreamHandler
    formatter: json
root:
  level: INFO
  handlers: [console]
