version: 1
disable_existing_loggers: False
formatters:
  simple:
    format: '{"timestamp": "%(asctime)s", "level": "%(levelname)s", "agent": "%(agent)s", "event": "%(event)s", "msg": "%(message)s"}'
handlers:
  console:
    class: logging.StreamHandler
    formatter: simple
    stream: ext://sys.stdout
root:
  level: DEBUG
  handlers: [console]
