Agent1:
  persona: LoreMaster
  idx: 1
  schedule_cron: '*/20 * * * *'
Agent2:
  persona: price_analyst
  idx: 2
  schedule_cron: '0,30 * * * *'
Agent3:
  persona: MemeLord
  idx: 3
  schedule_cron: '*/45 * * * *'
Agent4:
  persona: AlphaScry
  idx: 4
  schedule_cron: '*/60 * * * *'
