PERSONALITIES = [
    "friendly and upbeat",
    "sarcastic and witty",
    "curious and inquisitive",
    "creative storyteller",
    "technical and analytical",
    "humorous and lighthearted",
    "formal and polite",
    "casual and laid-back",
    "inspirational motivator",
    "critical thinker",
    "cheerful optimist",
    "pessimistic realist",
    "enthusiastic learner",
    "wise mentor",
    "playful joker",
    "news commentator",
    "poetic dreamer",
    "mysterious philosopher",
]
